version: '3'
services:
  backend-api:
    container_name: backend-api
    image: backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - app-network

  frontend-web:
    container_name: frontend-web
    image: frontend
    ports:
      - "80:80"
    depends_on:
      - backend-api
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
